// src/agent/metamask-agent/frontend/src/renderer/components/MetamaskButton.vue
<template>
  <div>
    <button class="button-metamask" @click="connectMetaMask">
      <img src="../assets/metamask_24x24.png" alt="Metamask Logo" class="metamask-logo">
      Connect
    </button>
  </div>
</template>

<script>


export default {
  name: 'MetamaskButton',
  methods: {
    async connectMetaMask() {

    }
  }
};
</script>

<style>
.button-metamask {
  background-color: #2F4F4F;
  border: 2px solid #FF7F50;
  border-radius: 30px;
  padding: 5px;
  color: #FF7F50;
  display: flex; /* Make the button a flex container */
  align-items: center; /* Center the contents vertically */
  justify-content: space-between; /* Space between the logo and text */
}
.button-metamask:hover{
  border: 2px solid #09256c;
  color: #09256c;
}
.metamask-logo {
  width: 24px;
  height: 24px;
  margin-right: 5px; /* Add spacing between the logo and text */
}
</style>

// electron-client/src/frontend/components/buttons/metaMaskButton.tsx
// libs
import React, { forwardRef } from 'react';
import Styled from 'styled-components';

// img
import metamaskLogo from './../../assets/images/metamask_fox_white_font.png';

export interface Props {
  connected: boolean;
  connecting: boolean;
  onClick: () => void;
}

type BadgeProps = {
  $connected: boolean;
  $connecting: boolean;
};

export default forwardRef<HTMLDivElement>((props: Props, ref) => {
  const { connected, connecting, onClick } = props;

  return (
    <MetaMaskButton.Wrapper onClick={onClick} ref={ref}>
      <MetaMaskButton.Logo src={metamaskLogo} />
      {!connecting && <MetaMaskButton.Badge $connected={connected} $connecting={connecting} />}
    </MetaMaskButton.Wrapper>
  );
});

const MetaMaskButton = {
  Wrapper: Styled.div`
    display: flex;
    position: relative;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    height: 50px;
    border-radius: 15px;
    margin: 0;
    background: ${(props) => props.theme.colors.core};
    cursor: pointer;
    transition: all 0.5s;
    border: none;
    z-index: 1;

    &:hover {
      background: ${(props) => props.theme.colors.emerald};
    }
  `,
  Logo: Styled.img`
    display: flex;
    width: 150px;
    height: 50px;
  `,
  Badge: Styled.div<BadgeProps>`
    display: flex;
    width: 10px;
    height: 10px;
    border-radius: 5px;
    background-color: ${(props) => (props.$connecting ? 'orange' : props.$connected ? 'green' : 'red')};
    margin-right: 10px;
  `,
};
